version: '3'

services:
  webapp:
   image: wesmackay/dockercatsdemo
   ports:
     - 5000:5000
   deploy:
     mode: replicated
     replicas: 3
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  proxy:
    image: wesmackay/nginx
    ports:
      - 80:80
    depends_on:
      - webapp
    networks: 
      - balance

networks:
  balance:
    driver: overlay
